### ISSUE TITLE
Bedre mono-repo støtte

### ISSUE THREAD

**Issue by routsi** [nais/docker-build-push#22]
Slik det ser ut for meg så er det lagt opp til at navnet på repoet blir satt til navnet på bildet, så for vårt team som har mono-repo med samme navn som teamet og flere applikasjoner så blir navnet på container bildene vi bygger `.../pensjonsbrev/pensjonsbrev`. Vi kan legge til app-navn gjennom `image_suffix` slik at det blir `.../pensjonsbrev/pensjonsbrev-pdf-bygger`, men jeg kunne gjerne tenkt meg at `image_name` ble eksponert som en parameter med default-verdi satt til navn på repo.

Ekstremt flisespikkeri, siden det ikke er ofte man forholder seg til image-navn.

**Comment by Kyrremann** [comment]
Ikke et konkret behov atm, kan heller fikse det hvis det dukker opp igjen.
