### ISSUE TITLE
Mulighet til å legge til `target` option for docker bygget

### ISSUE THREAD

**Issue by ugur93** [nais/docker-build-push#25]
Hadde vært fint å få mulighet til å utnytte docker sitt multi-stage bygg slik at det kan bygges ulike docker images for dev og prod (feks hvis vi ønsker shell støtte i dev for distroless bygg). Ref https://docs.docker.com/build/building/multi-stage/. 
Github action `docker/build-push-action` som benyttes i repoet støtter `target` option som brukes for å styre hvilken docker bygg stage som skal bygges. Eneste som må gjøres er å godta `target` som input variabel og sende det over som input til  `docker/build-push-action`

**Comment by Kyrremann** [comment]
Fixed in https://github.com/nais/docker-build-push/commit/9ce8f1518354baf349c250e960bf595c339318f1
